apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | default (include "companyservice.fullname" .) }}
  labels:
    {{- range $k, $v := .Values.deployment.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      {{- range $k, $v := .Values.deployment.labels }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $k, $v := .Values.deployment.labels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.deployment.serviceAccountName | default "myserviceaccount" }}
      containers:
        {{- range .Values.deployment.containers }}
        - name: {{ .name | quote }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .containerPort }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- if .resources }}
          resources:
            {{ toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{ toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            {{ toYaml .livenessProbe | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.deployment.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}      
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{ toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{ toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
