{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "companyservice.fullname" .) }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
