apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceaccount.clientid }}
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.serviceaccount.namespace }}
