namespace Husa.Quicklister.Abor.Api.Mappings.EnumTransformations
{
    using System;
    using Husa.Quicklister.Abor.Crosscutting.Extensions;
    using Husa.Quicklister.Abor.Domain.Enums;
    using Husa.Quicklister.Abor.Domain.Enums.Domain;
    using Husa.Quicklister.Extensions.Domain.Enums;
    using States = Husa.Extensions.Common.Enums.States;
    using Trestle = Husa.Downloader.CTX.Domain.Enums;

    public static class EnumMappings
    {
        public static HoaIncludes? ToCtxEnum(this Trestle.AssociationFeeIncludes value) => value switch
        {
            Trestle.AssociationFeeIncludes.CableTV => HoaIncludes.Cable,
            Trestle.AssociationFeeIncludes.CommonAreaMaintenance => HoaIncludes.CommonAreasMaintenance,
            Trestle.AssociationFeeIncludes.MaintenanceGrounds => HoaIncludes.MaintenanceGrounds,
            Trestle.AssociationFeeIncludes.MaintenanceStructure => HoaIncludes.MaintenanceStructure,
            Trestle.AssociationFeeIncludes.Internet => HoaIncludes.Internet,
            Trestle.AssociationFeeIncludes.Security => HoaIncludes.Security,
            Trestle.AssociationFeeIncludes.SeeRemarks => HoaIncludes.SeeRemarks,
            _ => null,
        };

        public static ListType? ToCtxEnum(this Trestle.PropertyType value) => value switch
        {
            Trestle.PropertyType.Residential or
            Trestle.PropertyType.CommercialSale => ListType.Residential,
            Trestle.PropertyType.Land => ListType.Lots,
            Trestle.PropertyType.ResidentialLease or
            Trestle.PropertyType.CommercialLease => ListType.Lease,
            _ => null,
        };

        public static MarketStatuses? ToCtxEnum(this Trestle.MlsStatus value) => value switch
        {
            Trestle.MlsStatus.Active => MarketStatuses.Active,
            Trestle.MlsStatus.ActiveUnderContract => MarketStatuses.ActiveUnderContract,
            Trestle.MlsStatus.Canceled or
            Trestle.MlsStatus.Withdrawn => MarketStatuses.Canceled,
            Trestle.MlsStatus.Closed => MarketStatuses.Closed,
            Trestle.MlsStatus.Hold => MarketStatuses.Hold,
            Trestle.MlsStatus.Pending => MarketStatuses.Pending,
            _ => throw new ArgumentException("Invalid MlsStatus value.", nameof(value)),
        };

        public static StreetType? ToCtxEnum(this Trestle.StreetSuffix? value) => value switch
        {
            Trestle.StreetSuffix.Alley => StreetType.ALY,
            Trestle.StreetSuffix.Arcade => StreetType.ARC,
            Trestle.StreetSuffix.Avenue => StreetType.AVE,
            Trestle.StreetSuffix.Beach => StreetType.BCH,
            Trestle.StreetSuffix.Bend => StreetType.BND,
            Trestle.StreetSuffix.Bluff => StreetType.BLF,
            Trestle.StreetSuffix.Bluffs => StreetType.BLFS,
            Trestle.StreetSuffix.Boulevard => StreetType.BLVD,
            Trestle.StreetSuffix.Branch => StreetType.BR,
            Trestle.StreetSuffix.Bridge => StreetType.BRG,
            Trestle.StreetSuffix.Brook => StreetType.BRK,
            Trestle.StreetSuffix.Bypass => StreetType.BYP,
            Trestle.StreetSuffix.Camp => StreetType.CP,
            Trestle.StreetSuffix.Canyon => StreetType.Canyon,
            Trestle.StreetSuffix.Cape => StreetType.Cape,
            Trestle.StreetSuffix.Causeway => StreetType.CSWY,
            Trestle.StreetSuffix.Circle => StreetType.CIR,
            Trestle.StreetSuffix.Cliff => StreetType.CLF,
            Trestle.StreetSuffix.Cliffs => StreetType.CLFS,
            Trestle.StreetSuffix.Club => StreetType.CLB,
            Trestle.StreetSuffix.Common => StreetType.CMN,
            Trestle.StreetSuffix.Corner => StreetType.COR,
            Trestle.StreetSuffix.Corners => StreetType.CORS,
            Trestle.StreetSuffix.Court => StreetType.CT,
            Trestle.StreetSuffix.Cove => StreetType.Cove,
            Trestle.StreetSuffix.Creek => StreetType.CRK,
            Trestle.StreetSuffix.Crescent => StreetType.CRSE,
            Trestle.StreetSuffix.Crest => StreetType.CRST,
            Trestle.StreetSuffix.Crossing => StreetType.XING,
            Trestle.StreetSuffix.Curve => StreetType.CURV,
            Trestle.StreetSuffix.Dale => StreetType.DL,
            Trestle.StreetSuffix.Dam => StreetType.DM,
            Trestle.StreetSuffix.Drive => StreetType.DR,
            Trestle.StreetSuffix.Estate => StreetType.EST,
            Trestle.StreetSuffix.Estates => StreetType.ESTS,
            Trestle.StreetSuffix.Expressway => StreetType.EXPY,
            Trestle.StreetSuffix.Extension => StreetType.EXT,
            Trestle.StreetSuffix.Fall => StreetType.FALL,
            Trestle.StreetSuffix.Falls => StreetType.FLS,
            Trestle.StreetSuffix.Field => StreetType.FLD,
            Trestle.StreetSuffix.Fields => StreetType.FLDS,
            Trestle.StreetSuffix.Flat => StreetType.FLT,
            Trestle.StreetSuffix.Flats => StreetType.FLTS,
            Trestle.StreetSuffix.Ford => StreetType.FRD,
            Trestle.StreetSuffix.Forest => StreetType.FRST,
            Trestle.StreetSuffix.Forge => StreetType.FRG,
            Trestle.StreetSuffix.Fork => StreetType.FRK,
            Trestle.StreetSuffix.Forks => StreetType.FRKS,
            Trestle.StreetSuffix.Garden => StreetType.GRN,
            Trestle.StreetSuffix.Gardens => StreetType.GRNS,
            Trestle.StreetSuffix.Glen => StreetType.GLN,
            Trestle.StreetSuffix.Green => StreetType.GRN,
            Trestle.StreetSuffix.Grove => StreetType.GRV,
            Trestle.StreetSuffix.Harbor => StreetType.HBR,
            Trestle.StreetSuffix.Haven => StreetType.HVN,
            Trestle.StreetSuffix.Heights => StreetType.HTS,
            Trestle.StreetSuffix.Highway => StreetType.HWY,
            Trestle.StreetSuffix.Hill => StreetType.HL,
            Trestle.StreetSuffix.Hills => StreetType.HLS,
            Trestle.StreetSuffix.Hollow => StreetType.HOLW,
            Trestle.StreetSuffix.Island => StreetType.IS,
            Trestle.StreetSuffix.Isle => StreetType.ISLE,
            Trestle.StreetSuffix.Junction => StreetType.JCT,
            Trestle.StreetSuffix.Key => StreetType.KY,
            Trestle.StreetSuffix.Knoll => StreetType.KNL,
            Trestle.StreetSuffix.Knolls => StreetType.KNLS,
            Trestle.StreetSuffix.Lake => StreetType.LK,
            Trestle.StreetSuffix.Lakes => StreetType.LKS,
            Trestle.StreetSuffix.Land => StreetType.LAND,
            Trestle.StreetSuffix.Landing => StreetType.LAND,
            Trestle.StreetSuffix.Lane => StreetType.LN,
            Trestle.StreetSuffix.Light => StreetType.LGT,
            Trestle.StreetSuffix.Lodge => StreetType.LDG,
            Trestle.StreetSuffix.Loop => StreetType.LOOP,
            Trestle.StreetSuffix.Manor => StreetType.MNR,
            Trestle.StreetSuffix.Meadow => StreetType.MDW,
            Trestle.StreetSuffix.Meadows => StreetType.MDWS,
            Trestle.StreetSuffix.Mews => StreetType.MEWS,
            Trestle.StreetSuffix.Mill => StreetType.ML,
            Trestle.StreetSuffix.Mills => StreetType.MLS,
            Trestle.StreetSuffix.Mount => StreetType.MT,
            Trestle.StreetSuffix.Mountain => StreetType.MTN,
            Trestle.StreetSuffix.Orchard => StreetType.ORCH,
            Trestle.StreetSuffix.Oval => StreetType.OVAL,
            Trestle.StreetSuffix.Park => StreetType.PARK,
            Trestle.StreetSuffix.Parkway => StreetType.PKWY,
            Trestle.StreetSuffix.Pass => StreetType.PASS,
            Trestle.StreetSuffix.Path => StreetType.PATH,
            Trestle.StreetSuffix.Pike => StreetType.PIKE,
            Trestle.StreetSuffix.Pine => StreetType.PINE,
            Trestle.StreetSuffix.Place => StreetType.PL,
            Trestle.StreetSuffix.Plain => StreetType.PLN,
            Trestle.StreetSuffix.Plains => StreetType.PLNS,
            Trestle.StreetSuffix.Plaza => StreetType.PLZ,
            Trestle.StreetSuffix.Point => StreetType.PT,
            Trestle.StreetSuffix.Port => StreetType.PRT,
            Trestle.StreetSuffix.Prairie => StreetType.PR,
            Trestle.StreetSuffix.Ranch => StreetType.RNCH,
            Trestle.StreetSuffix.Rapids => StreetType.RPDS,
            Trestle.StreetSuffix.Ridge => StreetType.RDG,
            Trestle.StreetSuffix.River => StreetType.RIV,
            Trestle.StreetSuffix.Road => StreetType.RD,
            Trestle.StreetSuffix.Row => StreetType.ROW,
            Trestle.StreetSuffix.Run => StreetType.RUN,
            Trestle.StreetSuffix.Shores => StreetType.SHR,
            Trestle.StreetSuffix.Skyway => StreetType.SKWY,
            Trestle.StreetSuffix.Spring => StreetType.SPG,
            Trestle.StreetSuffix.Springs => StreetType.SPGS,
            Trestle.StreetSuffix.Spur => StreetType.SPUR,
            Trestle.StreetSuffix.Square => StreetType.SQ,
            Trestle.StreetSuffix.Station => StreetType.STA,
            Trestle.StreetSuffix.Stream => StreetType.STRM,
            Trestle.StreetSuffix.Street => StreetType.ST,
            Trestle.StreetSuffix.Summit => StreetType.SMT,
            Trestle.StreetSuffix.Terrace => StreetType.TER,
            Trestle.StreetSuffix.Trace => StreetType.TRCE,
            Trestle.StreetSuffix.Track => StreetType.TRAK,
            Trestle.StreetSuffix.Trail => StreetType.TRL,
            Trestle.StreetSuffix.Valley => StreetType.VLY,
            Trestle.StreetSuffix.View => StreetType.VW,
            Trestle.StreetSuffix.Village => StreetType.VLG,
            Trestle.StreetSuffix.Vista => StreetType.VIS,
            Trestle.StreetSuffix.Walk => StreetType.WALK,
            Trestle.StreetSuffix.Way => StreetType.WAY,
            Trestle.StreetSuffix.Wells => StreetType.WLS,
            _ => null,
        };

        public static States? ToCtxEnum(this Trestle.StateOrProvince value) => value switch
        {
            Trestle.StateOrProvince.AL => States.Alabama,
            Trestle.StateOrProvince.AK => States.Alaska,
            Trestle.StateOrProvince.AR => States.Arkansas,
            Trestle.StateOrProvince.AZ => States.Arizona,
            Trestle.StateOrProvince.CA => States.California,
            Trestle.StateOrProvince.CO => States.Colorado,
            Trestle.StateOrProvince.CT => States.Connecticut,
            Trestle.StateOrProvince.DC => States.DC,
            Trestle.StateOrProvince.DE => States.Delaware,
            Trestle.StateOrProvince.FL => States.Florida,
            Trestle.StateOrProvince.GA => States.Georgia,
            Trestle.StateOrProvince.HI => States.Hawaii,
            Trestle.StateOrProvince.IA => States.Iowa,
            Trestle.StateOrProvince.ID => States.Idaho,
            Trestle.StateOrProvince.IL => States.Illinois,
            Trestle.StateOrProvince.IN => States.Indiana,
            Trestle.StateOrProvince.KS => States.Kansas,
            Trestle.StateOrProvince.KY => States.Kentucky,
            Trestle.StateOrProvince.LA => States.Louisiana,
            Trestle.StateOrProvince.MA => States.Massachusetts,
            Trestle.StateOrProvince.MD => States.Maryland,
            Trestle.StateOrProvince.ME => States.Maine,
            Trestle.StateOrProvince.MI => States.Michigan,
            Trestle.StateOrProvince.MN => States.Minnesota,
            Trestle.StateOrProvince.MO => States.Missouri,
            Trestle.StateOrProvince.MS => States.Mississippi,
            Trestle.StateOrProvince.MT => States.Montana,
            Trestle.StateOrProvince.NC => States.NorthCarolina,
            Trestle.StateOrProvince.ND => States.NorthDakota,
            Trestle.StateOrProvince.NE => States.Nebraska,
            Trestle.StateOrProvince.NH => States.NewHampshire,
            Trestle.StateOrProvince.NJ => States.NewJersey,
            Trestle.StateOrProvince.NM => States.NewMexico,
            Trestle.StateOrProvince.NV => States.Nevada,
            Trestle.StateOrProvince.NY => States.NewYork,
            Trestle.StateOrProvince.OK => States.Oklahoma,
            Trestle.StateOrProvince.OH => States.Ohio,
            Trestle.StateOrProvince.OR => States.Oregon,
            Trestle.StateOrProvince.PA => States.Pennsylvania,
            Trestle.StateOrProvince.RI => States.RhodeIsland,
            Trestle.StateOrProvince.SC => States.SouthCarolina,
            Trestle.StateOrProvince.SD => States.SouthDakota,
            Trestle.StateOrProvince.TN => States.Tennessee,
            Trestle.StateOrProvince.TX => States.Texas,
            Trestle.StateOrProvince.UT => States.Utah,
            Trestle.StateOrProvince.VA => States.Virginia,
            Trestle.StateOrProvince.VT => States.Vermont,
            Trestle.StateOrProvince.WA => States.Washington,
            Trestle.StateOrProvince.WI => States.Wisconsin,
            Trestle.StateOrProvince.WV => States.WestVirginia,
            Trestle.StateOrProvince.WY => States.Wyoming,
            _ => null,
        };

        public static PropertySubType? ToCtxEnum(this Trestle.PropertySubType value) => value switch
        {
            Trestle.PropertySubType.Condominium => PropertySubType.Condominium,
            Trestle.PropertySubType.SingleFamilyResidence => PropertySubType.SingleFamilyResidence,
            Trestle.PropertySubType.Townhouse => PropertySubType.Townhouse,
            _ => null,
        };

        public static LotDescription? ToCtxEnum(this Trestle.LotFeatures value) => value switch
        {
            Trestle.LotFeatures.BackstoGreenbeltPark => LotDescription.BackstoGreenbeltPark,
            Trestle.LotFeatures.BackYard => LotDescription.BackYard,
            Trestle.LotFeatures.Bluff => LotDescription.Bluff,
            Trestle.LotFeatures.CityLot => LotDescription.CityLot,
            Trestle.LotFeatures.ClosetoClubhouse => LotDescription.ClosetoClubhouse,
            Trestle.LotFeatures.CornerLot => LotDescription.CornerLot,
            Trestle.LotFeatures.CulDeSac => LotDescription.CulDeSac,
            Trestle.LotFeatures.FewTrees => LotDescription.FewTree,
            Trestle.LotFeatures.FrontYard => LotDescription.FrontYard,
            Trestle.LotFeatures.NearGolfCourse => LotDescription.NearGolfCourse,
            Trestle.LotFeatures.GentleSloping => LotDescription.GentleSloping,
            Trestle.LotFeatures.InteriorLot => LotDescription.InteriorLot,
            Trestle.LotFeatures.IrregularLot => LotDescription.IrregularLot,
            Trestle.LotFeatures.TreesLargeSize => LotDescription.TreesLarge,
            Trestle.LotFeatures.Level => LotDescription.Level,
            Trestle.LotFeatures.Landscaped => LotDescription.Landscaped,
            Trestle.LotFeatures.TreesMediumSize => LotDescription.TreesMedium,
            Trestle.LotFeatures.SprinklersManual => LotDescription.SprinklerManual,
            Trestle.LotFeatures.ModerateTrees => LotDescription.TreesModerate,
            Trestle.LotFeatures.None => LotDescription.None,
            Trestle.LotFeatures.NativePlants => LotDescription.NativePlants,
            Trestle.LotFeatures.OnGolfCourse => LotDescription.OnGolfCourse,
            Trestle.LotFeatures.PieShapedLot => LotDescription.PieShapedLot,
            Trestle.LotFeatures.PublicMaintainedRoad => LotDescription.PublicMaintainedRoad,
            Trestle.LotFeatures.NearPublicTransit => LotDescription.NearPublicTransit,
            Trestle.LotFeatures.SlopedDown => LotDescription.SlopedDown,
            Trestle.LotFeatures.SlopedUp => LotDescription.SlopedUp,
            Trestle.LotFeatures.TreesSmallSize => LotDescription.TreesSmall,
            Trestle.LotFeatures.SprinklersAutomatic => LotDescription.SprinklerAutomatic,
            Trestle.LotFeatures.SprinklersInFront => LotDescription.SprinklerInFront,
            Trestle.LotFeatures.SprinklersInGround => LotDescription.SprinklerInground,
            Trestle.LotFeatures.SprinklersPartial => LotDescription.SprinklerPartial,
            Trestle.LotFeatures.SprinklerRainSensor => LotDescription.SprinklerRainSensor,
            Trestle.LotFeatures.SprinklersInRear => LotDescription.SprinklerBackYard,
            Trestle.LotFeatures.SprinklersOnSide => LotDescription.SprinklerSideYard,
            Trestle.LotFeatures.Views => LotDescription.View,
            Trestle.LotFeatures.ManyTrees => LotDescription.TreesMany,
            Trestle.LotFeatures.ZeroLotLine => LotDescription.ZeroLotLine,
            _ => null,
        };

        public static HomeFaces? ToCtxEnum(this Trestle.DirectionFaces value) => value switch
        {
            Trestle.DirectionFaces.East => HomeFaces.East,
            Trestle.DirectionFaces.North => HomeFaces.North,
            Trestle.DirectionFaces.Northeast => HomeFaces.NorthEast,
            Trestle.DirectionFaces.Northwest => HomeFaces.NorthWest,
            Trestle.DirectionFaces.South => HomeFaces.South,
            Trestle.DirectionFaces.Southeast => HomeFaces.SouthEast,
            Trestle.DirectionFaces.Southwest => HomeFaces.SouthWest,
            Trestle.DirectionFaces.West => HomeFaces.West,
            _ => null,
        };

        public static Foundation? ToCtxEnum(this Trestle.FoundationDetails value) => value switch
        {
            Trestle.FoundationDetails.PillarPostPier => Foundation.PillarPostPier,
            Trestle.FoundationDetails.Slab => Foundation.Slab,
            _ => null,
        };

        public static RoofDescription? ToCtxEnum(this Trestle.Roof value) => value switch
        {
            Trestle.Roof.BuiltUp => RoofDescription.BuiltUp,
            Trestle.Roof.Composition => RoofDescription.Composition,
            Trestle.Roof.Copper => RoofDescription.Copper,
            Trestle.Roof.FlatTile => RoofDescription.FlatTile,
            Trestle.Roof.GreenRoof => RoofDescription.GreenRoof,
            Trestle.Roof.Shingle => RoofDescription.Shingle,
            Trestle.Roof.Slate => RoofDescription.Slate,
            Trestle.Roof.SpanishTile => RoofDescription.SpanishTile,
            Trestle.Roof.Synthetic => RoofDescription.Synthetic,
            Trestle.Roof.Tile => RoofDescription.Tile,
            Trestle.Roof.Wood => RoofDescription.Wood,
            _ => null,
        };

        public static ConstructionMaterials? ToCtxEnum(this Trestle.ConstructionMaterials value) => value switch
        {
            Trestle.ConstructionMaterials.Adobe => ConstructionMaterials.Adobe,
            Trestle.ConstructionMaterials.Asphalt => ConstructionMaterials.Asphalt,
            Trestle.ConstructionMaterials.AtticCrawlHatchwaysInsulated => ConstructionMaterials.AtticCrawlHatchwaysInsulated,
            Trestle.ConstructionMaterials.BlownInInsulation => ConstructionMaterials.BlownInInsulation,
            Trestle.ConstructionMaterials.Brick => ConstructionMaterials.Brick,
            Trestle.ConstructionMaterials.BrickVeneer => ConstructionMaterials.BrickVeneer,
            Trestle.ConstructionMaterials.Cedar => ConstructionMaterials.Cedar,
            Trestle.ConstructionMaterials.Clapboard => ConstructionMaterials.ClapBoard,
            Trestle.ConstructionMaterials.Concrete => ConstructionMaterials.Concrete,
            Trestle.ConstructionMaterials.Frame => ConstructionMaterials.Frame,
            Trestle.ConstructionMaterials.Glass => ConstructionMaterials.Glass,
            Trestle.ConstructionMaterials.HardiPlankType => ConstructionMaterials.HardiPlankType,
            Trestle.ConstructionMaterials.ICATRecessedLighting => ConstructionMaterials.ICatRecessedLighting,
            Trestle.ConstructionMaterials.ICFsInsulatedConcreteForms => ConstructionMaterials.InsulatedConcreteForms,
            Trestle.ConstructionMaterials.Log => ConstructionMaterials.Log,
            Trestle.ConstructionMaterials.Masonry => ConstructionMaterials.MasonryAllSides,
            Trestle.ConstructionMaterials.NaturalBuilding => ConstructionMaterials.NaturalBuilding,
            Trestle.ConstructionMaterials.RadiantBarrier => ConstructionMaterials.RadiantBarrier,
            Trestle.ConstructionMaterials.RecycledBioBasedInsulation => ConstructionMaterials.RecycledBioBasedInsulation,
            Trestle.ConstructionMaterials.RedwoodSiding => ConstructionMaterials.SidingRedwood,
            Trestle.ConstructionMaterials.WoodSiding => ConstructionMaterials.SidingWood,
            Trestle.ConstructionMaterials.VinylSiding => ConstructionMaterials.SidingVinyl,
            Trestle.ConstructionMaterials.SprayFoamInsulation => ConstructionMaterials.SprayFoamInsulation,
            Trestle.ConstructionMaterials.Stone => ConstructionMaterials.Stone,
            Trestle.ConstructionMaterials.StoneVeneer => ConstructionMaterials.StoneVeneer,
            Trestle.ConstructionMaterials.Stucco => ConstructionMaterials.Stucco,
            Trestle.ConstructionMaterials.SyntheticStucco => ConstructionMaterials.SyntheticStucco,
            _ => null,
        };

        public static FireplaceDescription? ToCtxEnum(this Trestle.FireplaceFeatures value) => value switch
        {
            Trestle.FireplaceFeatures.Bath => FireplaceDescription.Bathroom,
            Trestle.FireplaceFeatures.Bedroom => FireplaceDescription.Bedroom,
            Trestle.FireplaceFeatures.Circulating => FireplaceDescription.Circulating,
            Trestle.FireplaceFeatures.Decorative => FireplaceDescription.Decorative,
            Trestle.FireplaceFeatures.Den => FireplaceDescription.Den,
            Trestle.FireplaceFeatures.DoubleSided => FireplaceDescription.DoubleSided,
            Trestle.FireplaceFeatures.Electric => FireplaceDescription.Electric,
            Trestle.FireplaceFeatures.EPACertifiedWoodStove => FireplaceDescription.EPACertifiedWoodStove,
            Trestle.FireplaceFeatures.FamilyRoom => FireplaceDescription.FamilyRoom,
            Trestle.FireplaceFeatures.Gas => FireplaceDescription.Gas,
            Trestle.FireplaceFeatures.GasLog => FireplaceDescription.GasLog,
            Trestle.FireplaceFeatures.GasStarter => FireplaceDescription.GasStarter,
            Trestle.FireplaceFeatures.GreatRoom => FireplaceDescription.GreatRoom,
            Trestle.FireplaceFeatures.LivingRoom => FireplaceDescription.LivingRoom,
            Trestle.FireplaceFeatures.Masonry => FireplaceDescription.Masonry,
            Trestle.FireplaceFeatures.Metal => FireplaceDescription.Metal,
            Trestle.FireplaceFeatures.None => FireplaceDescription.None,
            Trestle.FireplaceFeatures.Outside => FireplaceDescription.Outside,
            Trestle.FireplaceFeatures.SeeThrough => FireplaceDescription.SeeThrough,
            Trestle.FireplaceFeatures.Ventless => FireplaceDescription.Ventless,
            Trestle.FireplaceFeatures.WoodBurning => FireplaceDescription.WoodBurning,
            _ => null,
        };

        public static Flooring? ToCtxEnum(this Trestle.Flooring value) => value switch
        {
            Trestle.Flooring.Carpet => Flooring.Carpet,
            Trestle.Flooring.Concrete => Flooring.Concrete,
            Trestle.Flooring.Laminate => Flooring.Laminate,
            Trestle.Flooring.Linoleum => Flooring.Linoleum,
            Trestle.Flooring.Marble => Flooring.Marble,
            Trestle.Flooring.Parquet => Flooring.Parquet,
            Trestle.Flooring.SeeRemarks => Flooring.SeeRemarks,
            Trestle.Flooring.Slate => Flooring.Slate,
            Trestle.Flooring.Terrazzo => Flooring.Terrazzo,
            Trestle.Flooring.Tile => Flooring.Tile,
            Trestle.Flooring.Vinyl => Flooring.Vinyl,
            Trestle.Flooring.Wood => Flooring.Wood,
            _ => null,
        };

        public static LaundryLocation? ToCtxEnum(this Trestle.LaundryFeatures value) => value switch
        {
            Trestle.LaundryFeatures.InKitchen => LaundryLocation.Kitchen,
            Trestle.LaundryFeatures.LaundryCloset => LaundryLocation.LaundryCloset,
            Trestle.LaundryFeatures.LaundryRoom => LaundryLocation.LaundryRoom,
            Trestle.LaundryFeatures.MainLevel => LaundryLocation.MainLevel,
            Trestle.LaundryFeatures.UpperLevel => LaundryLocation.UpperLevel,
            _ => null,
        };

        public static GarageDescription? ToCtxEnum(this Trestle.ParkingFeatures value) => value switch
        {
            Trestle.ParkingFeatures.AlleyAccess => GarageDescription.AlleyAccess,
            Trestle.ParkingFeatures.Attached => GarageDescription.Attached,
            Trestle.ParkingFeatures.CircularDriveway => GarageDescription.CircularDriveway,
            Trestle.ParkingFeatures.Concrete => GarageDescription.Concrete,
            Trestle.ParkingFeatures.Covered => GarageDescription.Covered,
            Trestle.ParkingFeatures.Detached => GarageDescription.Detached,
            Trestle.ParkingFeatures.DirectAccess => GarageDescription.DirectAccess,
            Trestle.ParkingFeatures.DoorMulti => GarageDescription.DoorMulti,
            Trestle.ParkingFeatures.DoorSingle => GarageDescription.DoorSingle,
            Trestle.ParkingFeatures.DriveThrough => GarageDescription.DriveThrough,
            Trestle.ParkingFeatures.Driveway => GarageDescription.Driveway,
            Trestle.ParkingFeatures.ElectricGate => GarageDescription.ElectricGate,
            Trestle.ParkingFeatures.GarageDoorOpener => GarageDescription.GarageDoorOpener,
            Trestle.ParkingFeatures.GarageFacesFront => GarageDescription.GarageFacesFront,
            Trestle.ParkingFeatures.GarageFacesRear => GarageDescription.GarageFacesRear,
            Trestle.ParkingFeatures.GarageFacesSide => GarageDescription.GarageFacesSide,
            Trestle.ParkingFeatures.Gravel => GarageDescription.Gravel,
            Trestle.ParkingFeatures.InsideEntrance => GarageDescription.InsideEntrance,
            Trestle.ParkingFeatures.KitchenLevel => GarageDescription.KitchenLevel,
            Trestle.ParkingFeatures.Lighted => GarageDescription.Lighted,
            Trestle.ParkingFeatures.Oversized => GarageDescription.Oversized,
            Trestle.ParkingFeatures.Private => GarageDescription.Private,
            Trestle.ParkingFeatures.SideBySide => GarageDescription.SideBySide,
            Trestle.ParkingFeatures.Storage => GarageDescription.Storage,
            Trestle.ParkingFeatures.Tandem => GarageDescription.Tandem,
            _ => null,
        };
        public static PatioAndPorchFeatures? ToCtxEnum(this Trestle.PatioAndPorchFeatures value) => value switch
        {
            Trestle.PatioAndPorchFeatures.Awnings => PatioAndPorchFeatures.Awnings,
            Trestle.PatioAndPorchFeatures.Covered => PatioAndPorchFeatures.Covered,
            Trestle.PatioAndPorchFeatures.Deck => PatioAndPorchFeatures.Deck,
            Trestle.PatioAndPorchFeatures.Enclosed => PatioAndPorchFeatures.Enclosed,
            Trestle.PatioAndPorchFeatures.FrontPorch => PatioAndPorchFeatures.FrontPorch,
            Trestle.PatioAndPorchFeatures.GlassEnclosed => PatioAndPorchFeatures.GlassEnclosed,
            Trestle.PatioAndPorchFeatures.MosquitoSystem => PatioAndPorchFeatures.MosquitoSystem,
            Trestle.PatioAndPorchFeatures.None => PatioAndPorchFeatures.None,
            Trestle.PatioAndPorchFeatures.Patio => PatioAndPorchFeatures.Patio,
            Trestle.PatioAndPorchFeatures.Porch => PatioAndPorchFeatures.Porch,
            Trestle.PatioAndPorchFeatures.RearPorch => PatioAndPorchFeatures.RearPorch,
            Trestle.PatioAndPorchFeatures.Screened => PatioAndPorchFeatures.Screened,
            Trestle.PatioAndPorchFeatures.SeeRemarks => PatioAndPorchFeatures.SeeRemarks,
            Trestle.PatioAndPorchFeatures.SidePorch => PatioAndPorchFeatures.SidePorch,
            Trestle.PatioAndPorchFeatures.Terrace => PatioAndPorchFeatures.Terrace,
            Trestle.PatioAndPorchFeatures.WrapAround => PatioAndPorchFeatures.WrapAround,
            _ => null,
        };

        public static InteriorFeatures? ToCtxEnum(this Trestle.InteriorOrRoomFeatures value) => value switch
        {
            Trestle.InteriorOrRoomFeatures.MultiplePrimarySuites => InteriorFeatures.TwoPrimarySuites,
            Trestle.InteriorOrRoomFeatures.Bar => InteriorFeatures.Bar,
            Trestle.InteriorOrRoomFeatures.Bookcases => InteriorFeatures.Bookcases,
            Trestle.InteriorOrRoomFeatures.BreakfastBar => InteriorFeatures.BreakfastBar,
            Trestle.InteriorOrRoomFeatures.BuiltinFeatures => InteriorFeatures.BuiltinFeatures,
            Trestle.InteriorOrRoomFeatures.CeilingFans => InteriorFeatures.CeilingFans,
            Trestle.InteriorOrRoomFeatures.BeamedCeilings => InteriorFeatures.CeilingsBeamed,
            Trestle.InteriorOrRoomFeatures.CathedralCeilings => InteriorFeatures.CeilingsCathedral,
            Trestle.InteriorOrRoomFeatures.CofferedCeilings => InteriorFeatures.CeilingsCoffered,
            Trestle.InteriorOrRoomFeatures.HighCeilings => InteriorFeatures.CeilingsHigh,
            Trestle.InteriorOrRoomFeatures.TrayCeilings => InteriorFeatures.CeilingsTray,
            Trestle.InteriorOrRoomFeatures.VaultedCeilings => InteriorFeatures.CeilingsVaulted,
            Trestle.InteriorOrRoomFeatures.Chandelier => InteriorFeatures.Chandelier,
            Trestle.InteriorOrRoomFeatures.CrownMolding => InteriorFeatures.CrownMolding,
            Trestle.InteriorOrRoomFeatures.DoubleVanity => InteriorFeatures.DoubleVanity,
            Trestle.InteriorOrRoomFeatures.EatinKitchen => InteriorFeatures.EatinKitchen,
            Trestle.InteriorOrRoomFeatures.EntranceFoyer => InteriorFeatures.EntranceFoyer,
            Trestle.InteriorOrRoomFeatures.FrenchDoorsAtriumDoors => InteriorFeatures.FrenchDoors,
            Trestle.InteriorOrRoomFeatures.HighSpeedInternet => InteriorFeatures.HighSpeedInternet,
            Trestle.InteriorOrRoomFeatures.InLawFloorplan => InteriorFeatures.InLawFloorplan,
            Trestle.InteriorOrRoomFeatures.InteriorSteps => InteriorFeatures.InteriorSteps,
            Trestle.InteriorOrRoomFeatures.KitchenIsland => InteriorFeatures.KitchenIsland,
            Trestle.InteriorOrRoomFeatures.LowFlowPlumbingFixtures => InteriorFeatures.LowFlowPlumbingFixtures,
            Trestle.InteriorOrRoomFeatures.MultipleDiningAreas => InteriorFeatures.MultipleDiningAreas,
            Trestle.InteriorOrRoomFeatures.MultipleLivingAreas => InteriorFeatures.MultipleLivingAreas,
            Trestle.InteriorOrRoomFeatures.NaturalWoodwork => InteriorFeatures.NaturalWoodwork,
            Trestle.InteriorOrRoomFeatures.NoInteriorSteps => InteriorFeatures.NoInteriorSteps,
            Trestle.InteriorOrRoomFeatures.None => InteriorFeatures.None,
            Trestle.InteriorOrRoomFeatures.OpenFloorplan => InteriorFeatures.OpenFloorplan,
            Trestle.InteriorOrRoomFeatures.Pantry => InteriorFeatures.Pantry,
            Trestle.InteriorOrRoomFeatures.MainLevelPrimary => InteriorFeatures.PrimaryBedroomonMain,
            Trestle.InteriorOrRoomFeatures.RecessedLighting => InteriorFeatures.RecessedLighting,
            Trestle.InteriorOrRoomFeatures.SeeRemarks => InteriorFeatures.SeeRemarks,
            Trestle.InteriorOrRoomFeatures.SmartHome => InteriorFeatures.SmartHome,
            Trestle.InteriorOrRoomFeatures.SmartThermostat => InteriorFeatures.SmartThermostat,
            Trestle.InteriorOrRoomFeatures.SoakingTub => InteriorFeatures.SoakingTub,
            Trestle.InteriorOrRoomFeatures.SolarTubes => InteriorFeatures.SolarTubes,
            Trestle.InteriorOrRoomFeatures.SoundSystem => InteriorFeatures.SoundSystem,
            Trestle.InteriorOrRoomFeatures.Storage => InteriorFeatures.Storage,
            Trestle.InteriorOrRoomFeatures.TrackLighting => InteriorFeatures.TrackLighting,
            Trestle.InteriorOrRoomFeatures.WalkInClosets => InteriorFeatures.WalkInClosets,
            Trestle.InteriorOrRoomFeatures.WaterSenseFixtures => InteriorFeatures.WaterSenseFixtures,
            Trestle.InteriorOrRoomFeatures.WiredforData => InteriorFeatures.WiredforData,
            Trestle.InteriorOrRoomFeatures.WiredforSound => InteriorFeatures.WiredforSound,
            _ => null,
        };

        public static Appliances? ToCtxEnum(this Trestle.Appliances value) => value switch
        {
            Trestle.Appliances.BarFridge => Appliances.BarFridge,
            Trestle.Appliances.BuiltInElectricOven => Appliances.BuiltInElectricOven,
            Trestle.Appliances.BuiltInElectricRange => Appliances.BuiltInElectricRange,
            Trestle.Appliances.BuiltInFreezer => Appliances.BuiltInFreezer,
            Trestle.Appliances.BuiltInGasOven => Appliances.BuiltInGasOven,
            Trestle.Appliances.BuiltInGasRange => Appliances.BuiltInGasRange,
            Trestle.Appliances.BuiltInOven => Appliances.BuiltInOven,
            Trestle.Appliances.BuiltInRange => Appliances.BuiltInRange,
            Trestle.Appliances.BuiltInRefrigerator => Appliances.BuiltInRefrigerator,
            Trestle.Appliances.ConvectionOven => Appliances.ConvectionOven,
            Trestle.Appliances.Cooktop => Appliances.Cooktop,
            Trestle.Appliances.Dishwasher => Appliances.Dishwasher,
            Trestle.Appliances.Disposal => Appliances.Disposal,
            Trestle.Appliances.DownDraft => Appliances.DownDraft,
            Trestle.Appliances.Dryer => Appliances.Dryer,
            Trestle.Appliances.ElectricCooktop => Appliances.ElectricCooktop,
            Trestle.Appliances.ElectricRange => Appliances.ElectricRange,
            Trestle.Appliances.ENERGYSTARQualifiedAppliances => Appliances.EnergyStarQualifiedAppliances,
            Trestle.Appliances.ENERGYSTARQualifiedDishwasher => Appliances.EnergyStarQualifiedDishwasher,
            Trestle.Appliances.ENERGYSTARQualifiedDryer => Appliances.EnergyStarQualifiedDryer,
            Trestle.Appliances.ENERGYSTARQualifiedFreezer => Appliances.EnergyStarQualifiedFreezer,
            Trestle.Appliances.ENERGYSTARQualifiedRefrigerator => Appliances.EnergyStarQualifiedRefrigerator,
            Trestle.Appliances.ENERGYSTARQualifiedWasher => Appliances.EnergyStarQualifiedWasher,
            Trestle.Appliances.ENERGYSTARQualifiedWaterHeater => Appliances.EnergyStarQualifiedWaterHeater,
            Trestle.Appliances.ExhaustFan => Appliances.ExhaustFan,
            Trestle.Appliances.GasCooktop => Appliances.GasCooktop,
            Trestle.Appliances.GasRange => Appliances.GasRange,
            Trestle.Appliances.InstantHotWater => Appliances.InstantHotWater,
            Trestle.Appliances.Microwave => Appliances.Microwave,
            Trestle.Appliances.None => Appliances.None,
            Trestle.Appliances.Oven => Appliances.Oven,
            Trestle.Appliances.ElectricOven => Appliances.OvenElectric,
            Trestle.Appliances.FreeStandingElectricOven => Appliances.OvenFreeStandingElectric,
            Trestle.Appliances.FreeStandingGasOven => Appliances.OvenFreeStandingGas,
            Trestle.Appliances.GasOven => Appliances.OvenGas,
            Trestle.Appliances.DoubleOven => Appliances.OvenDouble,
            Trestle.Appliances.PlumbedForIceMaker => Appliances.PlumbedForIceMaker,
            Trestle.Appliances.Range => Appliances.Range,
            Trestle.Appliances.FreeStandingElectricRange => Appliances.RangeFreeStandingElectric,
            Trestle.Appliances.FreeStandingRange => Appliances.RangeFreeStanding,
            Trestle.Appliances.FreeStandingGasRange => Appliances.RangeFreeStandingGas,
            Trestle.Appliances.RangeHood => Appliances.RangeHood,
            Trestle.Appliances.Refrigerator => Appliances.Refrigerator,
            Trestle.Appliances.FreeStandingRefrigerator => Appliances.RefrigeratorFreeStanding,
            Trestle.Appliances.SeeRemarks => Appliances.SeeRemarks,
            Trestle.Appliances.SelfCleaningOven => Appliances.SelfCleaningOven,
            Trestle.Appliances.SolarHotWater => Appliances.SolarHotWater,
            Trestle.Appliances.StainlessSteelAppliances => Appliances.StainlessSteelAppliance,
            Trestle.Appliances.TanklessWaterHeater => Appliances.TanklessWaterHeater,
            Trestle.Appliances.TrashCompactor => Appliances.TrashCompactor,
            Trestle.Appliances.VentedExhaustFan => Appliances.VentedExhaustFan,
            Trestle.Appliances.WasherDryer => Appliances.WasherDryer,
            Trestle.Appliances.ElectricWaterHeater => Appliances.WaterHeaterElectric,
            Trestle.Appliances.GasWaterHeater => Appliances.WaterHeaterGas,
            _ => null,
        };

        public static Fencing? ToCtxEnum(this Trestle.Fencing value) => value switch
        {
            Trestle.Fencing.BackYard => Fencing.BackYard,
            Trestle.Fencing.Block => Fencing.Block,
            Trestle.Fencing.Brick => Fencing.Brick,
            Trestle.Fencing.Gate => Fencing.Gate,
            Trestle.Fencing.Masonry => Fencing.Masonry,
            Trestle.Fencing.None => Fencing.None,
            Trestle.Fencing.Partial => Fencing.Partial,
            Trestle.Fencing.Privacy => Fencing.Privacy,
            Trestle.Fencing.Security => Fencing.Security,
            Trestle.Fencing.Stone => Fencing.Stone,
            Trestle.Fencing.Vinyl => Fencing.Vinyl,
            Trestle.Fencing.Wood => Fencing.Wood,
            Trestle.Fencing.WroughtIron => Fencing.WroughtIron,
            _ => null,
        };

        public static WaterSource? ToCtxEnum(this Trestle.WaterSource value) => value switch
        {
            Trestle.WaterSource.Public => WaterSource.Public,
            Trestle.WaterSource.Private => WaterSource.Private,
            Trestle.WaterSource.MunicipalUtilityDistrict => WaterSource.MUD,
            _ => null,
        };

        public static View? ToCtxEnum(this Trestle.ViewTrestle value) => value switch
        {
            Trestle.ViewTrestle.Bridges => View.Bridges,
            Trestle.ViewTrestle.Canal => View.Canal,
            Trestle.ViewTrestle.Canyon => View.Canyon,
            Trestle.ViewTrestle.City => View.City,
            Trestle.ViewTrestle.CityLights => View.CityLights,
            Trestle.ViewTrestle.CreekStream => View.CreekStream,
            Trestle.ViewTrestle.Downtown => View.Downtown,
            Trestle.ViewTrestle.Garden => View.Garden,
            Trestle.ViewTrestle.GolfCourse => View.GolfCourse,
            Trestle.ViewTrestle.Hills => View.HillCountry,
            Trestle.ViewTrestle.Lake => View.Lake,
            Trestle.ViewTrestle.Marina => View.Marina,
            Trestle.ViewTrestle.Neighborhood => View.Neighborhood,
            Trestle.ViewTrestle.None => View.None,
            Trestle.ViewTrestle.Orchard => View.Orchard,
            Trestle.ViewTrestle.Panoramic => View.Panoramic,
            Trestle.ViewTrestle.ParkGreenbelt => View.ParkGreenbelt,
            Trestle.ViewTrestle.Pasture => View.Pasture,
            Trestle.ViewTrestle.Pond => View.Pond,
            Trestle.ViewTrestle.Pool => View.Pool,
            Trestle.ViewTrestle.River => View.River,
            Trestle.ViewTrestle.Rural => View.Rural,
            Trestle.ViewTrestle.Skyline => View.Skyline,
            Trestle.ViewTrestle.TreesWoods => View.TreesWoods,
            Trestle.ViewTrestle.Vineyard => View.Vineyard,
            Trestle.ViewTrestle.Water => View.Water,
            _ => null,
        };

        public static ExteriorFeatures? ToCtxEnum(this Trestle.ExteriorFeatures value) => value switch
        {
            Trestle.ExteriorFeatures.Balcony => ExteriorFeatures.Balcony,
            Trestle.ExteriorFeatures.ExteriorSteps => ExteriorFeatures.ExteriorSteps,
            Trestle.ExteriorFeatures.ElectricGrill => ExteriorFeatures.GrillElectric,
            Trestle.ExteriorFeatures.GasGrill => ExteriorFeatures.GrillGas,
            Trestle.ExteriorFeatures.Lighting => ExteriorFeatures.Lighting,
            Trestle.ExteriorFeatures.NoExteriorSteps => ExteriorFeatures.NoExteriorSteps,
            Trestle.ExteriorFeatures.None => ExteriorFeatures.None,
            Trestle.ExteriorFeatures.OutdoorGrill => ExteriorFeatures.OutdoorGrill,
            Trestle.ExteriorFeatures.Playground => ExteriorFeatures.Playground,
            Trestle.ExteriorFeatures.PrivateYard => ExteriorFeatures.PrivateYard,
            Trestle.ExteriorFeatures.TennisCourts => ExteriorFeatures.TennisCourts,
            _ => null,
        };

        public static NeighborhoodAmenities? ToCtxEnum(this Trestle.CommunityFeatures value) => value switch
        {
            Trestle.CommunityFeatures.Clubhouse => NeighborhoodAmenities.Clubhouse,
            Trestle.CommunityFeatures.CommunityMailbox => NeighborhoodAmenities.ClusterMailbox,
            Trestle.CommunityFeatures.CommonGroundsArea => NeighborhoodAmenities.CommonGrounds,
            Trestle.CommunityFeatures.Courtyard => NeighborhoodAmenities.Courtyard,
            Trestle.CommunityFeatures.Curbs => NeighborhoodAmenities.Curbs,
            Trestle.CommunityFeatures.DogPark => NeighborhoodAmenities.DogParkPlayArea,
            Trestle.CommunityFeatures.Fishing => NeighborhoodAmenities.Fishing,
            Trestle.CommunityFeatures.FitnessCenter => NeighborhoodAmenities.FitnessCenter,
            Trestle.CommunityFeatures.GameRoom => NeighborhoodAmenities.GameRoom,
            Trestle.CommunityFeatures.Gated => NeighborhoodAmenities.Gated,
            Trestle.CommunityFeatures.GolfCourseCommunity => NeighborhoodAmenities.GolfCourse,
            Trestle.CommunityFeatures.InternetAccess => NeighborhoodAmenities.HighSpeedInternet,
            Trestle.CommunityFeatures.KitchenFacilities => NeighborhoodAmenities.KitchenFacilities,
            Trestle.CommunityFeatures.Lake => NeighborhoodAmenities.Lake,
            Trestle.CommunityFeatures.MediaRoom => NeighborhoodAmenities.MediaCenterMovieTheatre,
            Trestle.CommunityFeatures.None => NeighborhoodAmenities.None,
            Trestle.CommunityFeatures.Park => NeighborhoodAmenities.Park,
            Trestle.CommunityFeatures.PetAmenities => NeighborhoodAmenities.PetAmenities,
            Trestle.CommunityFeatures.GardenArea => NeighborhoodAmenities.PicnicArea,
            Trestle.CommunityFeatures.Playground => NeighborhoodAmenities.Playground,
            Trestle.CommunityFeatures.Pool => NeighborhoodAmenities.Pool,
            Trestle.CommunityFeatures.SeeRemarks => NeighborhoodAmenities.SeeRemarks,
            Trestle.CommunityFeatures.Sidewalks => NeighborhoodAmenities.Sidewalks,
            Trestle.CommunityFeatures.SportCourts => NeighborhoodAmenities.SportCourtFacility,
            Trestle.CommunityFeatures.StorageFacilities => NeighborhoodAmenities.Storage,
            Trestle.CommunityFeatures.StreetLights => NeighborhoodAmenities.StreetLights,
            Trestle.CommunityFeatures.TennisCourts => NeighborhoodAmenities.TennisCourt,
            Trestle.CommunityFeatures.TrailsPaths => NeighborhoodAmenities.WalkBikeHikeJogTrails,
            _ => null,
        };

        public static HeatingSystem? ToCtxEnum(this Trestle.Heating value) => value switch
        {
            Trestle.Heating.Ceiling => HeatingSystem.Ceiling,
            Trestle.Heating.Central => HeatingSystem.Central,
            Trestle.Heating.Electric => HeatingSystem.Electric,
            Trestle.Heating.ENERGYSTARQualifiedEquipment => HeatingSystem.EnergyStarQualifiedEquipment,
            Trestle.Heating.ExhaustFan => HeatingSystem.ExhaustFan,
            Trestle.Heating.Fireplaces => HeatingSystem.Fireplace,
            Trestle.Heating.NaturalGas => HeatingSystem.NaturalGas,
            Trestle.Heating.PassiveSolar => HeatingSystem.PassiveSolar,
            Trestle.Heating.Propane => HeatingSystem.Propane,
            Trestle.Heating.Zoned => HeatingSystem.Zoned,
            _ => null,
        };

        public static CoolingSystem? ToCtxEnum(this Trestle.Cooling value) => value switch
        {
            Trestle.Cooling.CeilingFans => CoolingSystem.CeilingFan,
            Trestle.Cooling.CentralAir => CoolingSystem.CentralAir,
            Trestle.Cooling.Dual => CoolingSystem.Dual,
            Trestle.Cooling.Electric => CoolingSystem.Electric,
            Trestle.Cooling.ENERGYSTARQualifiedEquipment => CoolingSystem.EnergyStarQualifiedEquipment,
            Trestle.Cooling.MultiUnits => CoolingSystem.MultiUnits,
            Trestle.Cooling.Zoned => CoolingSystem.Zoned,
            _ => null,
        };

        public static WaterSewer? ToCtxEnum(this Trestle.Sewer value) => value switch
        {
            Trestle.Sewer.AerobicSeptic => WaterSewer.AerobicSeptic,
            Trestle.Sewer.EngineeredSeptic => WaterSewer.EngineeredSeptic,
            Trestle.Sewer.MunicipalUtilityDistrict => WaterSewer.MUD,
            Trestle.Sewer.PrivateSewer => WaterSewer.PrivateSewer,
            Trestle.Sewer.PublicSewer => WaterSewer.PublicSewer,
            Trestle.Sewer.SepticTank => WaterSewer.SepticTank,
            _ => null,
        };

        public static UtilitiesDescription? ToCtxEnum(this Trestle.Utilities value) => value switch
        {
            Trestle.Utilities.AboveGroundUtilities => UtilitiesDescription.AboveGroundUtilities,
            Trestle.Utilities.CableAvailable => UtilitiesDescription.CableAvailable,
            Trestle.Utilities.ElectricityAvailable => UtilitiesDescription.ElectricityAvailable,
            Trestle.Utilities.HighSpeedInternetAvailable => UtilitiesDescription.InternetCable,
            Trestle.Utilities.FiberOpticAvailable => UtilitiesDescription.InternetFiber,
            Trestle.Utilities.SatelliteInternetAvailable => UtilitiesDescription.InternetSatelliteOther,
            Trestle.Utilities.NaturalGasAvailable => UtilitiesDescription.NaturalGasAvailable,
            Trestle.Utilities.PhoneAvailable => UtilitiesDescription.PhoneAvailable,
            Trestle.Utilities.Propane => UtilitiesDescription.Propane,
            Trestle.Utilities.SewerAvailable => UtilitiesDescription.SewerAvailable,
            Trestle.Utilities.SewerConnected => UtilitiesDescription.SewerConnected,
            Trestle.Utilities.UndergroundUtilities => UtilitiesDescription.UndergroundUtilities,
            Trestle.Utilities.WaterAvailable => UtilitiesDescription.WaterAvailable,
            Trestle.Utilities.WaterConnected => UtilitiesDescription.WaterConnected,
            _ => null,
        };

        public static AcceptableFinancing? ToCtxEnum(this Trestle.ListingTerms value) => value switch
        {
            Trestle.ListingTerms.Cash => AcceptableFinancing.Cash,
            Trestle.ListingTerms.Conventional => AcceptableFinancing.Conventional,
            Trestle.ListingTerms.FHA => AcceptableFinancing.FHA,
            Trestle.ListingTerms.SeeRemarks => AcceptableFinancing.SeeRemarks,
            Trestle.ListingTerms.LeaseBack => AcceptableFinancing.LeaseBack,
            Trestle.ListingTerms.TexasVet => AcceptableFinancing.TexasVet,
            Trestle.ListingTerms.USDALoan => AcceptableFinancing.USDALoan,
            Trestle.ListingTerms.VALoan => AcceptableFinancing.VALoan,
            _ => null,
        };

        public static CommissionType? ToCtxEnum(this Trestle.CompensationType value) => value switch
        {
            Trestle.CompensationType.Item => CommissionType.Amount,
            Trestle.CompensationType.Item1 => CommissionType.Percent,
            _ => null,
        };

        public static BillingFrequency? ToCtxEnum(this Trestle.FeeFrequency value) => value switch
        {
            Trestle.FeeFrequency.Annually => BillingFrequency.Annually,
            Trestle.FeeFrequency.Monthly => BillingFrequency.Monthly,
            Trestle.FeeFrequency.Quarterly => BillingFrequency.Quarterly,
            Trestle.FeeFrequency.SemiAnnually => BillingFrequency.SemiAnnually,
            _ => null,
        };

        public static LockBoxType? ToCtxEnum(this Trestle.LockBoxType value) => value switch
        {
            Trestle.LockBoxType.Combo => LockBoxType.Combo,
            Trestle.LockBoxType.Electronic or
            Trestle.LockBoxType.Supra => LockBoxType.Supra,
            Trestle.LockBoxType.None => LockBoxType.None,
            Trestle.LockBoxType.SeeRemarks => LockBoxType.SeeRemarks,
            _ => null,
        };

        public static ShowingRequirements? ToCtxEnum(this Trestle.ShowingRequirements value) => value switch
        {
            Trestle.ShowingRequirements.ListingAgentPresent => ShowingRequirements.AgentOrOwnerPresent,
            Trestle.ShowingRequirements.AppointmentOnly => ShowingRequirements.AppointmentOnly,
            Trestle.ShowingRequirements.CallBeforeShowing => ShowingRequirements.CallFirst,
            Trestle.ShowingRequirements.GoDirect => ShowingRequirements.Go,
            Trestle.ShowingRequirements.Lockbox => ShowingRequirements.Lockbox,
            Trestle.ShowingRequirements.KeyInOffice => ShowingRequirements.KeyInOffice,
            Trestle.ShowingRequirements.CallOwner => ShowingRequirements.CallOwner,
            Trestle.ShowingRequirements.SecuritySystem => ShowingRequirements.SecuritySystem,
            Trestle.ShowingRequirements.SeeShowingInstructions => ShowingRequirements.SeeShowingInstructions,
            Trestle.ShowingRequirements.ShowingService => ShowingRequirements.ShowingService,
            _ => null,
        };

        public static SecurityFeatures? ToCtxEnum(this Trestle.SecurityFeatures value) => value switch
        {
            Trestle.SecurityFeatures.CarbonMonoxideDetectors => SecurityFeatures.CarbonMonoxideDetectors,
            Trestle.SecurityFeatures.FireAlarm => SecurityFeatures.FireAlarm,
            Trestle.SecurityFeatures.FireSprinklerSystem => SecurityFeatures.FireSprinklerSystem,
            Trestle.SecurityFeatures.GatedwithGuard => SecurityFeatures.GatedwithGuard,
            Trestle.SecurityFeatures.None => SecurityFeatures.None,
            Trestle.SecurityFeatures.Prewired => SecurityFeatures.Prewired,
            Trestle.SecurityFeatures.SecuredGarageParking => SecurityFeatures.SecuredGarageParking,
            Trestle.SecurityFeatures.SecuritySystem => SecurityFeatures.SecuritySystem,
            Trestle.SecurityFeatures.SecuritySystemLeased => SecurityFeatures.SecuritySystemLeased,
            Trestle.SecurityFeatures.SecuritySystemOwned => SecurityFeatures.SecuritySystemOwned,
            Trestle.SecurityFeatures.SeeRemarks => SecurityFeatures.SeeRemarks,
            Trestle.SecurityFeatures.SmokeDetectors => SecurityFeatures.SmokeDetectors,
            _ => null,
        };

        public static WindowFeatures? ToCtxEnum(this Trestle.WindowFeatures value) => value switch
        {
            Trestle.WindowFeatures.BayWindows => WindowFeatures.BayWindows,
            Trestle.WindowFeatures.Blinds => WindowFeatures.Blinds,
            Trestle.WindowFeatures.DoublePaneWindows => WindowFeatures.DoublePaneWindows,
            Trestle.WindowFeatures.ENERGYSTARQualifiedWindows => WindowFeatures.EnergyStarQualifiedWindows,
            Trestle.WindowFeatures.InsulatedWindows => WindowFeatures.InsulatedWindows,
            Trestle.WindowFeatures.None => WindowFeatures.None,
            Trestle.WindowFeatures.PlantationShutters => WindowFeatures.PlantationShutters,
            Trestle.WindowFeatures.Screens => WindowFeatures.Screens,
            Trestle.WindowFeatures.Shutters => WindowFeatures.Shutters,
            Trestle.WindowFeatures.StormWindows => WindowFeatures.StormWindows,
            Trestle.WindowFeatures.Vinyl => WindowFeatures.VinylWindows,
            _ => null,
        };

        public static WaterfrontFeatures? ToCtxEnum(this Trestle.WaterfrontFeatures value) => value switch
        {
            Trestle.WaterfrontFeatures.CanalFront => WaterfrontFeatures.CanalFront,
            Trestle.WaterfrontFeatures.Creek => WaterfrontFeatures.Creek,
            Trestle.WaterfrontFeatures.LakeFront => WaterfrontFeatures.LakeFront,
            Trestle.WaterfrontFeatures.LakePrivileges => WaterfrontFeatures.LakePrivileges,
            Trestle.WaterfrontFeatures.None => WaterfrontFeatures.None,
            Trestle.WaterfrontFeatures.Pond => WaterfrontFeatures.Pond,
            Trestle.WaterfrontFeatures.RiverFront => WaterfrontFeatures.RiverFront,
            Trestle.WaterfrontFeatures.Waterfront => WaterfrontFeatures.WaterFront,
            _ => null,
        };

        public static SaleTerms? ToCtxEnum(this Trestle.BuyerFinancing value) => value switch
        {
            Trestle.BuyerFinancing.Cash => SaleTerms.Cash,
            Trestle.BuyerFinancing.TexasVet => SaleTerms.TexasVet,
            Trestle.BuyerFinancing.Conventional => SaleTerms.Conventional,
            Trestle.BuyerFinancing.USDA => SaleTerms.UsdaEligible,
            Trestle.BuyerFinancing.FHA => SaleTerms.FHA,
            Trestle.BuyerFinancing.VA => SaleTerms.VA,
            _ => null,
        };

        public static Stories? ToStories(this Trestle.Levels? value) => value switch
        {
            Trestle.Levels.One => Stories.One,
            Trestle.Levels.OneandOneHalf => Stories.OnePointFive,
            Trestle.Levels.Two => Stories.Two,
            Trestle.Levels.ThreeOrMore => Stories.ThreePlus,
            Trestle.Levels.MultiLevelUnit => Stories.MultiLevel,
            _ => null,
        };

        public static ElementarySchool? ToElementarySchool(this string school) => school switch
        {
            "Callison" => ElementarySchool.NeysaCallison,
            _ => school.GetEnumFromSchools<ElementarySchool>(),
        };
}
}
