pr:
  branches:
    include:
    - develop
    - release/*
    - hotfix/*
    - master
  paths:
    include:
      - Husa.Quicklister.Abor.Api.Client

trigger:
  branches:
    include:
    - develop
    - release/*
    - hotfix/*
    - master
  paths:
    include:
      - Husa.Quicklister.Abor.Api.Client

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Husa.Quicklister.Abor.Api.Client.csproj'
    restoreArguments: '/property:Configuration=Release'
    feedsToUse: 'select'
    vstsFeed: 'f820f957-6781-4cd6-b5f5-e720c189507f/891ce0ed-37b7-4336-b1fe-079c0525a171'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/Husa.Quicklister.Abor.Api.Client.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Husa.Quicklister.Abor.Api.Client.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()
