service:
  enabled: true
  name: quicklisterabor
  type: ClusterIP
  port: 80
  targetPort: 8080
  selector:
    app: quicklisterabor

deployment:
  name: quicklisterabor
  namespace: dev
  labels:
    app: quicklisterabor
    "azure.workload.identity/use": "true"
  replicas: 1
  serviceAccountName: myserviceaccount
  containers:
    - name: quicklisterabor
      image: "acrhomesusadev.azurecr.io/quicklister.abor"   # full image here
      tag: "latest"
      imagePullPolicy: "IfNotPresent"
      containerPort: 8080
      env:
        - name: AZURE_APPCONFIGURATION_ENDPOINT
          value: "https://aac-husa-cus-dev.azconfig.io"
        - name: AZURE_CLIENT_ID
          value: 32313547-be6e-4ae3-bfd5-330845d6da8b # terraform output app_client_id
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      # readinessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: 8080
      #   initialDelaySeconds: 5
      #   periodSeconds: 10
      # livenessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: 8080
      #   initialDelaySeconds: 30
      #   periodSeconds: 20
  nodeSelector: {}
  tolerations: []
  affinity: {}
  imagePullSecrets: [] 

# NEW ingress section
ingress:
  enabled: true
  className: "nginx" 
  annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-azuredns
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: qlabor.aks.homesusa.com
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: wildcard-aks-homesusa-tls
      hosts:
        - qlabor.aks.homesusa.com
