name: CI - Build and Test

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'Husa.Quicklister.Abor.sln'
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/HomesUSA-com/index.json'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Configure GitHub Packages authentication
      run: |
        dotnet nuget remove source github || true
        dotnet nuget add source https://nuget.pkg.github.com/HomesUSA-com/index.json \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --verbosity normal

