name: CD - Publish Packages

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'Husa.Quicklister.Abor.sln'
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/HomesUSA-com/index.json'

jobs:
  publish-packages:
    name: Build and Publish NuGet Packages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Configure GitHub Packages authentication
      run: |
        dotnet nuget remove source github || true
        dotnet nuget add source https://nuget.pkg.github.com/HomesUSA-com/index.json \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.PACKAGE_PAT }} \
          --store-password-in-clear-text
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Pack NuGet packages (builds and packs in one step)
      run: |
        mkdir -p ./nupkgs
        dotnet pack Husa.Quicklister.Abor.Api.Client/Husa.Quicklister.Abor.Api.Client.csproj \
          --configuration Release --no-restore --output ./nupkgs
        dotnet pack Husa.Quicklister.Abor.ServiceBus.Contracts/Husa.Quicklister.Abor.ServiceBus.Contracts.csproj \
          --configuration Release --no-restore --output ./nupkgs
        ls -la ./nupkgs/
      
    - name: Publish packages to GitHub Packages
      run: |
        for package in ./nupkgs/*.nupkg; do
          echo "Publishing: $package"
          dotnet nuget push "$package" \
            --source github \
            --api-key ${{ secrets.PACKAGE_PAT }} \
            --skip-duplicate \
            || echo "Failed or duplicate: $package"
        done
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nupkgs/*.nupkg
        retention-days: 30

