name: CD - Publish Packages

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'Husa.Quicklister.Abor.sln'
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/HomesUSA-com/index.json'

jobs:
  publish-packages:
    name: Build and Publish NuGet Packages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Configure GitHub Packages authentication
      run: |
        dotnet nuget remove source github || true
        dotnet nuget add source https://nuget.pkg.github.com/HomesUSA-com/index.json \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Build solution (Release)
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
      
    - name: Pack NuGet packages
      run: dotnet pack ${{ env.SOLUTION_FILE }} --configuration Release --no-build --output ./nupkgs
      
    - name: Publish packages to GitHub Packages
      run: |
        for package in ./nupkgs/*.nupkg; do
          echo "Publishing: $package"
          dotnet nuget push "$package" \
            --source github \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate \
            || echo "Failed or duplicate: $package"
        done
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./nupkgs/*.nupkg
        retention-days: 30

